# -*- mode: ruby -*-
# vi: set ft=ruby :

user = ENV['USER']
home = ENV['HOME']
nic = ENV['NIC']

Vagrant.configure("2") do |config|
	
	#credit goes to Stefan Wrobel https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck
	config.vm.provider :virtualbox do |vb|
		host = RbConfig::CONFIG['host_os']
		# Give VM 1/4 system memory & access to all cpu cores on the host
		if host =~ /darwin/
			cpus = `sysctl -n hw.ncpu`.to_i
			# sysctl returns Bytes and we need to convert to MB
			mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
		elsif host =~ /linux/
			cpus = `nproc`.to_i
			# meminfo shows KB and we need to convert to MB
			mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
		else # sorry Windows folks, I can't help you
			cpus = 2
			mem = 1024
		end
		vb.customize ["modifyvm", :id, "--memory", mem]
		vb.customize ["modifyvm", :id, "--cpus", cpus]
	end
	
	config.vm.define :otc_dev do |otc_dev|
    	otc_dev.vm.box = "steffenhoenig/debian7.9-i386"
    	otc_dev.vm.provision :shell, :path => './scripts/debian/7/bootstrap.sh', args: user
    	otc_dev.vm.provision :shell, :path => './scripts/debian/common/jre-oracle-7.sh'
		otc_dev.vm.hostname = "os-" + user
		otc_dev.vm.network :public_network, :bridge => nic
		otc_dev.ssh.forward_agent = true
		otc_dev.ssh.insert_key = true
		#dev.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
		otc_dev.vm.provision :shell, :path => './scripts/debian/common/jre-oracle-8.sh'
		otc_dev.vm.provision "shell", inline: "sudo update-java-alternatives -s java-7-oracle"
		otc_dev.vm.provision :shell, :path => './scripts/debian/common/openthinclient-installer.sh'
		otc_dev.vm.provision :shell, :path => './scripts/debian/common/enable-all-repos.sh'
		otc_dev.vm.provision :shell, :path => './scripts/debian/common/tcos-dev.sh'

		otc_dev.vm.synced_folder home, "/home/" + user, id: "home" + user 
		otc_dev.vm.synced_folder "../", "/vagrant"
	end
	
	config.vm.define :otc_prod do |otc_prod|
    	otc_prod.vm.box = "steffenhoenig/debian7.9-i386"
    	otc_prod.vm.provision :shell, :path => './scripts/debian/7/bootstrap.sh', args: user
    	otc_prod.vm.provision :shell, :path => './scripts/debian/common/jre-oracle-7.sh'
		otc_prod.vm.hostname = "openthinclient-server"
		otc_prod.vm.network :public_network, :bridge => "eth0"
		otc_prod.vm.synced_folder "../", "/vagrant"
		otc_prod.vm.provision "shell", inline: "sudo cp /vagrant/data/tools/archive_metadata /usr/bin"
		otc_prod.vm.provision :shell, :path => './scripts/debian/common/openthinclient-installer.sh'
		otc_prod.vm.provider :virtualbox do |vb|
			# modify mem to full usage
			mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024
			if mem >= 2048
				mem = 2048
			end
			vb.customize ["modifyvm", :id, "--memory", mem]
		end
	end
    
    config.vm.define :java_dev do |java_dev|
        java_dev.vm.box = "tutum/node"
        java_dev.vm.hostname = "java-buildserver" 
        java_dev.vm.network :public_network, :bridge => "eth0"
        java_dev.ssh.forward_agent = true
        java_dev.ssh.insert_key = true
        java_dev.vm.provision :shell, :path => './scripts/debian/common/java-build-deps.sh'
    	# modify mem to full usage
       	java_dev.vm.provider :virtualbox do |vb|
			mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024
			if mem >= 2048
				mem = 2048
			end
			vb.customize ["modifyvm", :id, "--memory", mem]
		end
    end
      
        config.ssh.forward_agent = true
        config.ssh.forward_x11 = true
end
