# -*- mode: ruby -*-
# vi: set ft=ruby :

user = ENV['USER']
home = ENV['HOME']

Vagrant.configure("2") do |config|
	config.vm.box = "steffenhoenig/debian7.9-i386"
	config.vm.provision :shell, :path => './scripts/debian/7/bootstrap.sh', args: user
	config.vm.provision :shell, :path => './scripts/debian/common/jre-oracle-7.sh'
	
	#credit goes to Stefan Wrobel https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck
	config.vm.provider :virtualbox do |vb|
		host = RbConfig::CONFIG['host_os']
		# Give VM 1/4 system memory & access to all cpu cores on the host
		if host =~ /darwin/
			cpus = `sysctl -n hw.ncpu`.to_i
			# sysctl returns Bytes and we need to convert to MB
			mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
		elsif host =~ /linux/
			cpus = `nproc`.to_i
			# meminfo shows KB and we need to convert to MB
			mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
		else # sorry Windows folks, I can't help you
			cpus = 2
			mem = 1024
		end
		vb.customize ["modifyvm", :id, "--memory", mem]
		vb.customize ["modifyvm", :id, "--cpus", cpus]
	end
	
	config.vm.define :dev do |dev|
		dev.vm.hostname = "os-" + user
		dev.vm.network :public_network
		dev.ssh.forward_agent = true
		dev.ssh.insert_key = false
		dev.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
		dev.vm.provision :shell, :path => './scripts/debian/common/jre-oracle-8.sh'
		dev.vm.provision "shell", inline: "sudo update-java-alternatives -s java-7-oracle"
		dev.vm.provision :shell, :path => './scripts/debian/common/openthinclient-installer.sh'
		dev.vm.provision :shell, :path => './scripts/debian/common/enable-all-repos.sh'
		dev.vm.provision :shell, :path => './scripts/debian/common/tcos-dev.sh'


		dev.vm.network "private_network", type: "dhcp"
		dev.vm.synced_folder home, "/home/" + user, id: "home" + user, 
			:nfs => true,
			:mount_options => ["actimeo=2"]
		dev.vm.synced_folder "../", "/vagrant"
	end
	
	config.vm.define :prod do |prod|
		prod.vm.hostname = "openthinclient-server"
		prod.vm.network :public_network, :bridge => "eth0"
		prod.vm.synced_folder "../", "/vagrant"
		prod.vm.provision "shell", inline: "sudo cp /vagrant/data/tools/archive_metadata /usr/bin"
		prod.vm.provision :shell, :path => './scripts/debian/common/openthinclient-installer.sh'
		prod.vm.provider :virtualbox do |vb|
			# modify mem to full usage
			mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024
			if mem >= 2048
				mem = 2048
			end
			vb.customize ["modifyvm", :id, "--memory", mem]
		end
	end
end
