#!/usr/bin/env python

# Standard modules
import os

# TCOS modules
import pytcos.tcos as tcos

# Binary to execute
executable = "/opt/#PACKAGE#/bin/#PACKAGE#"

l = tcos.Launcher()

# Get Paramter entry (see #PACKAGE#.xml)
parameter = l.ENTRY.get('Application.Parameter', '')

# And start executable
returncode = os.system(' '.join([
	executable,
	parameter.strip()
	]))
