#!/usr/bin/env bash

function read_section(){
#usage:
#eval $(read_section <Path to ini> <Section>)

    [ -z "$1" ] && exit 1

    if [ "$1" == "-g" ];then
        shift
        show_global=1
    fi

    local ini_file="$1"
    local ini_section=${2:-$(default_section $1)}
    parse $ini_file $ini_section

}

#usage:
#parse <file> <section>
function parse(){
    ini_file=$1

    if (( $show_global ));then
      ini_section="global"
    else
      ini_section=$2
    fi

    result=$(\
    sed -e 's/[[:space:]]*\=[[:space:]]*/=/g' \
	-e 's/;.*$//' \
	-e 's/[[:space:]]*$//' \
	-e 's/^[[:space:]]*//' \
	-e "s/^\(.*\)=\([^\"']*\)$/\1=\"\2\"/" \
       < "$ini_file" \
       | sed -n -e "/^\[$ini_section\]/,/^\s*\[/{/^[^;].*\=.*/p;}")

    for r in $result;do
      echo $r
    done
}

function default_section(){
#usage:
#section=default_section <Path to ini>

#[ -f "$1" ] || exit 1

   local ini_file="$1"

   section_xp='^\[(.*)\]$' # matches [Sections], match[1]: Sections

   while read line;do
       if [[ $line =~ $section_xp ]];then
           # don't print global section
           if [ "${BASH_REMATCH[1]}" == "global" ];then
             continue
           else
             echo "${BASH_REMATCH[1]}"
           fi
           exit 0
       fi
   done < $ini_file
   exit 1
}

function sourced() {
      local -i rc=1
      [[ 'source' ==  ${FUNCNAME[1]} ]] && rc=0
      return $rc
}

# __main__

sourced ||  read_section $@
