#!/usr/bin/env bash

function read_section(){
#usage:
#eval $(read_section <Path to ini> <Section>)

    [ -z "$1" ] || [ -z "$2" ] && exit 1

    local ini_file="$1"
    local ini_section="$2"

    sed -e 's/[[:space:]]*\=[[:space:]]*/=/g' \
	-e 's/;.*$//' \
	-e 's/[[:space:]]*$//' \
	-e 's/^[[:space:]]*//' \
	-e "s/^\(.*\)=\([^\"']*\)$/\1=\"\2\"/" \
       < "$ini_file" \
	| sed -n -e "/^\[$ini_section\]/,/^\s*\[/{/^[^;].*\=.*/p;}"
}

function default_section(){
#usage:
#section=default_section <Path to ini>

#[ -f "$1" ] || exit 1

   local ini_file="$1"

   section_xp='^\[(.*)\]$' # matches [Sections], match[1]: Sections

   while read line;do
       if [[ $line =~ $section_xp ]];then
           echo "${BASH_REMATCH[1]}"
           exit 0
       fi
   done < $ini_file
   exit 1
}
