#! /bin/sh
#
# archive_metadata.sh
# Copyright (C) 2015 plumps <plumps@lobsang.local>
#
# Distributed under terms of the MIT license.
#
set -e
[ "$1" != "" ] && cd "$1"

apt-ftparchive packages . > Packages
gzip -9cf < Packages > Packages.gz
bzip2 -9cf < Packages > Packages.bz2
apt-ftparchive sources . > Sources
gzip -9cf < Sources > Sources.gz
bzip2 -9cf < Sources > Sources.bz2
apt-ftparchive release . > Release
